name: Test

on:
  push:
    branches:
      - 'master'
      - 'rc-*'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Audits
        run: npm audit --production

      - name: Lints
        run: npm run lint:ci

      - name: Test
        run: npm run test
